/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevendedorRouteImport } from './routes/revendedor'
import { Route as OndeEncontrarRouteImport } from './routes/onde-encontrar'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as IndexRouteImport } from './routes/index'

const RevendedorRoute = RevendedorRouteImport.update({
  id: '/revendedor',
  path: '/revendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeEncontrarRoute = OndeEncontrarRouteImport.update({
  id: '/onde-encontrar',
  path: '/onde-encontrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/onde-encontrar': typeof OndeEncontrarRoute
  '/revendedor': typeof RevendedorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/onde-encontrar': typeof OndeEncontrarRoute
  '/revendedor': typeof RevendedorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/onde-encontrar': typeof OndeEncontrarRoute
  '/revendedor': typeof RevendedorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cardapio' | '/onde-encontrar' | '/revendedor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cardapio' | '/onde-encontrar' | '/revendedor'
  id: '__root__' | '/' | '/cardapio' | '/onde-encontrar' | '/revendedor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardapioRoute: typeof CardapioRoute
  OndeEncontrarRoute: typeof OndeEncontrarRoute
  RevendedorRoute: typeof RevendedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revendedor': {
      id: '/revendedor'
      path: '/revendedor'
      fullPath: '/revendedor'
      preLoaderRoute: typeof RevendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-encontrar': {
      id: '/onde-encontrar'
      path: '/onde-encontrar'
      fullPath: '/onde-encontrar'
      preLoaderRoute: typeof OndeEncontrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardapioRoute: CardapioRoute,
  OndeEncontrarRoute: OndeEncontrarRoute,
  RevendedorRoute: RevendedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
